config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  
  resources :users, only: [:index,:edit, :update]
  resources :groups,only: [:index, :new, :create, :edit, :update] do
     resources :messages, only: [:index, :create]
     namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
      end
  end
end

app/models/message.rb
class Message < ApplicationRecord

belongs_to :group
belongs_to :user

validates :content, presence: true, unless: :image?
mount_uploader :image, ImageUploader
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  before_action :get_group
  
  def index
    respond_to do |format| 
      format.json { @messages = @group.messages.where('id > ?',params[:id])}
    end 
  end

  private
  def get_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_group

    def index
        @message = Message.new
        @messages = @group.messages.includes(:user)
    end

    def create
        @message = @group.messages.new(message_params)
        if @message.save
            respond_to do |format|
                format.html { redirect_to group_messages_path }
                format.json
            end
        else
            @messages = @group.messages.includes(:user)
            flash.now[:alert] = 'メッセージを入力してください。'
            render :index
        end
    end

    private

    def message_params
        params.require(:message).permit(:content,:image).merge(user_id: current_user.id)
    end

    def set_group
        @group = Group.find(params[:group_id])
    end
    
end

app/views/messages/index.html.haml
.body
  .body-main
    = render 'shared/side_bar'

    .body-right

      .body-right--header

        .crrent-group
          .header--group-name
            = @group.name
          .header--member-list
            Members:
            - @group.users.each do |user|
              =user.name
        = link_to edit_group_path(@group) ,class:  "link" do
          .header__edit
            edit
      .body-right--main
        =render 'shared/message.html.haml'


      .body-right--footer
        .form
          = form_for [@group, @message] do |f|
            = f.text_field :content, class: 'form__message',id: 'form__message', placeholder: 'type a message'
            .form__mask
              = f.label :image, class: 'form__mask__image' do
                = fa_icon 'picture-o', class: 'icon'
                = f.file_field :image, class: 'hidden'
            = f.submit 'Send', class: 'form__submit',id: 'form__submit'