config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  
  resources :users, only: [:index,:edit, :update]
  resources :groups,only: [:index, :new, :create, :edit, :update] do
     resources :messages, only: [:index, :create]
     namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
      end
  end
end

app/views/shared/_message.html.haml
.comment
    .upper-info
        %p{"data-group-id"=> "#{@group.id}"}
        - @messages.each do |message|
            .group__comment
                %strong
                    = message.user.name
                .comment__date
                    = message.created_at.strftime('%Y-%m-%d %H:%M:%S')
                .comment__text
                    %p{"data-message-comment"=> "#{message.id}"} #{message.content}
                    = image_tag message.image.url, class: 'lower-message__image',"data-message-comment"=> "#{message.id}" if message.image.present?

app/views/shared/_side_bar.html.haml
.body-left
  .body-left--header
    .left-header--user-name
      %strong
        = "#{current_user.name}"
    .left-header__icon
      = link_to "/groups/new" ,class: "link" do
        %i.fa.fa-edit
      = link_to "/users/#{current_user.id}/edit" ,class: " link" do
        %i.fa.fa-cog
  .body-left--group
    .groups
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group
            .link
              .group__name.link
                = group.name
              .group__message.link
                = group.show_last_message
              